language: ruby
cache:
- bundler
install:
- bundle install
rvm:
- 1.9.3
- 2.0
- 2.1
- 2.2
notifications:
  email:
    recipients:
    - sensu-plugin@sensu-plugins.io
    on_success: change
    on_failure: always
script:
- bundle exec rake default
- gem build sensu-plugins-pacemaker.gemspec
- gem install sensu-plugins-pacemaker-*.gem
deploy:
  provider: rubygems
  api_key:
    secure: QW6Lcv2Qe01ixg32gvHGtq52kt+6ihNiGVQbtoNC42O+x9HH0eVyluqJn7YSi4xi6AbGm9Og4mfD9vXscxGhWaDC+LMTWrFSjSwhHa2NEcqOgmmljhD01Id/glFK8F7ZwbaCXt7MaJy1BwHVauLeahbhDUh9IGzrdfQGBYyqNzQ=
  gem: sensu-plugins-pacemaker
  on:
    ags: true
    all_branches: true
    rvm: 1.9.3
    rvm: 2.0
    rvm: 2.1
    rvm: 2.2
    repo: sensu-plugins/sensu-plugins-pacemaker
